### ISSUE TITLE
Request: "Push-to-Talk" für Talkback (RME TotalMix)

### ISSUE THREAD

**Issue by DeltaAudio** [shells-dw/streamdeck-totalmix#10]
Hey shells-dw,

first of all - thank you so much for this great plug-in!
We're considering replacing our ARC with a StreamDeck now, thanks to your work!
Therefore, one - for our workflow significant - question came up:

Would it be possible to integrate a "Push-to-Talk" function for the Talkback?
Idealy with a two-state visual feedback?
Of course one could argue, if you have to push the button, you won't see a visual feedback anyway - but since it is possible to cascade two StreamDecks or add the elgato footswitch/ pedal, the visual aspect would come in really handy.

Would be great if that 'd be possible at all - and if you 'd find the time for this, course!

Thanks again for all your effort here
und beste Grüße aus Hamburg :)

**Comment by shells-dw** [comment]
Cheers DeltaAudio,

I've published a new version just now - have a look in the Releases folder of this repo and check it out.
The "OSC Triger Global Function" module has a "Hold Mode" now that should be able to do exactly that (once you enabled it) for all global features.
Additionally I've added the option to support two custom icons that switch when triggered - in case you like to change the icons to your own. However, the included icon will (should? ;-) ) change its color as well.

I don't really work with Firefaces anymore, I switched to UA interfaces quite a while ago. I still have a Fireface UC laying around and used that to make the updates and verify the changes on the newest RME driver on Win 10 - however I didn't really thoroughly test those, so ... in case something doesn't work as expected, let me know.

Beste Grüße aus Berlin zurück nach Hamburg :-)
