### ISSUE TITLE
Similar for Loupedeck?

### ISSUE THREAD

**Issue by Limeqvist** [shells-dw/streamdeck-totalmix#12]
Hi!

I really like your plugins, would you be willing to discuss about creating something similar for us at Loupedeck? Please send me an email at emil.lindqvist@loupedeck.com if you are interested! :)

**Comment by JasonGosling** [comment]
I use these on my stream deck and they are excellent. Our company is rolling out loupedecks too soon so +1. You guys should pay him what he asks ;-)

**Comment by shells-dw** [comment]
> Hi!
> 
> I really like your plugins, would you be willing to discuss about creating something similar for us at Loupedeck? Please send me an email at [emil.lindqvist@loupedeck.com](mailto:emil.lindqvist@loupedeck.com) if you are interested! :)

Hi Emil, sent you an email :)
I'll be closing the issue here now, let's continue talking via mail.


> I use these on my stream deck and they are excellent. Our company is rolling out loupedecks too soon so +1. You guys should pay him what he asks ;-)

Haha, thanks a bunch Jason, much appreciated :)
