### ISSUE TITLE
Functions only work after restarting the StreamDeck software

### ISSUE THREAD

**Issue by CreaturesFarley** [shells-dw/streamdeck-totalmix#13]
Hiya. I'm using the plugin on my Windows 11 machine with a Fireface 400. I have a few mute functions mapped. They work fine right after the Streamdeck software has launched, but they go unresponsive after about 15 minutes. I can kick start them into working again by quitting the Streamdeck app and reopening.

**Comment by shells-dw** [comment]
Hey :)
Yeah, I had issues with the mirror-thing reported with Windows 11 before... #11 
Didn't seem to happen on any Windows 10 box, could never reproduce and no one opened an issue for it with anything other than Windows 11.

I didn't upgrade my own machine until literally last weekend... did a quick test on the plugin and it worked, but to be fair I didn't let it sit for over 15 minutes.

Right now I'm recoding the plugin for the Loupedeck (new toy with more options 😅 ) and basically do a full rewrite for it anyway.
Once I'm done with that, I'll give the StreamDeck plugin another look, now that I'm hopefully able to figure out what's actually going on there... also I might find some better ways to do things with the rewrite, so we'll see.
Got to ask you to hang on for a couple of weeks though. I'll get back to it eventually.
Thanks for reporting the specifics with the 15 minute timeout by the way, not necessarily something you accidentally stumble upon while debugging and testing 👍 
Cheers!

**Comment by CreaturesFarley** [comment]
Ooh, intriguing! I've been eyeing up the Loupedeck for a while.

Definitely lemme know if you ever make those updates, and hopefully they'll fix things! For what it's worth, the plugin is SUPER useful, and one of the prime things I use my Stream Deck for, so thank you for that!

**Comment by CreaturesFarley** [comment]
Ohai! Just testing out the beta version. It's working nicely so far. There's a teensy bit of latency between pressing the button and the action happening, but that's fine for my uses! Thank you so much!
