### ISSUE TITLE
de.shells.totalmix.exe uses 100% of 1 CPU core all the time

### ISSUE THREAD

**Issue by AntonTrapp** [shells-dw/streamdeck-totalmix#15]
First: TNX for that awesome plugin!

You just need to install the plugin, throw any action on a key, after booting - you don't even need to use it.

1 CPU core goes to 100%. Current Windows 11 22H2 with fixes, latest version of Elgato 6.x.

Please ping me for further information, ... - really want to have that awesome plugin running..

1 thing that's probably different to most systems: I do not always have my RME device turned on (especially not during boot time).

**Comment by shells-dw** [comment]
Hi Anton,
thx.
Quick question, do you use the version from the Elgato Marketplace-thing or the latest version from [Releaes](https://github.com/shells-dw/streamdeck-totalmix/releases/tag/v3.1.4) here?
I've been updating the plugin a lot recently (and solved some issues with Win 11) but haven't asked Elgato to push a new version to the store until I'm sure it's actually running well. 😉 
The version here should not do anything with the device being offline or disconnected, instead the buttons should all go red and tell you "no connection".

**Comment by shells-dw** [comment]
Hi Anton,
I released [v3.2.0](https://github.com/shells-dw/streamdeck-totalmix/releases/tag/v3.2.0) yesterday that fixed a couple of bugs including crashes and potentially break the mirroring after some time (well, hopefully, but so far it's looking good), you might want to update to 3.2.0 :)

> Paypal account for large coffe?
>
Well, not sure if that was a serious question... anyhow: I don't have created that account for coffee tips, I have it anyways, so why not put it in here in case someone wants to donate a couple of bucks if they find the plugin helpful and if it might have saved them from buying the 130EUR RME ARC. Never expected but always appreciated.

StreamDeck+ looks nice. I don't own one and I'm not planning on getting one, so don't expect this plugin to ever work for it (unless Elgato supplies me with a device - then for sure I'd be happy to adapt the plugin 😉 )

I own a similiar priced [Loupedeck Live](https://loupedeck.com/de/products/loupedeck-live/) though, for which I [rewrote the plugin ](https://github.com/shells-dw/loupedeck-totalmix)as well. Offers 6 dials in contrary to 4 as well 😉 

Anyway, frohe Weihnachten und einen guten Rutsch!
Grüße!
