### ISSUE TITLE
Volume Up / Volume Down Function in Plugin

### ISSUE THREAD

**Issue by DerThomasLange** [shells-dw/streamdeck-totalmix#24]
Dear Dominik,

thank you for your work, you've programmed a great feature which I personally love to use with my Babyface Pro. :-)

One question: Is there a feature inside the plugin, that allows me to simply reduce or increase the volume of my speakers/headphones as the physical turning wheel on the Babyface Pro does?
The only feature I can find in the several button functions is, that you can choose one specific volume value. 
So when you press the button it jumps on that fix defined volume. 

What I would like to have are two buttons on my stream deck for volume control. One button, that increases the volume by let's say 5 db, every time you press it, and a second button, that simply decreases the volume by the same amount, when it's pressed. 
Is this feature already available and I'm just to stupid to find it or is it indeed missing?
If so, would you kindly show me how to set it, otherwise could you implement this feature in the next version?

Thank you very much and keep up your great work!

Best regards from Bavaria Germany,

Thomas

**Comment by shells-dw** [comment]
Servus Thomas,

dankeschön! Positive Rückmeldungen sind immer willkommen 😃 

I understood what you're trying to achieve - and that's currently not possible.

I think it's a very good idea though, I really like it and I'm going to implement it soon.
I never thought of doing it that way, but it's actually kind of obvious now that you mention it 😆 

With one limitation though: I wouldn't try to go for fixed dB values, RME uses a logarithmic scale I couldn't figure out (it's not 20\*Log10 or 20\*Log20 or anything defining anything related to dB mathematically I could think of - unless I messed up my math when trying it out) that is then converted to a float value with 8 decimals for the OSC transmission... so, long story short, 5dB probably wouldn't be 5dB, the further away from 0dB you get, the more it would become. I did a lot of trial and error when writing my Loupedeck plugin which supports this for the dials, but couldn't figure it out.
Hence I'd go for the steps RME uses for the mouse wheel action on the faders in the TotalMix UI and maybe add a multiplier option so you can actually do bigger steps - I'll implement it and test it out and see what's reasonable. We can fine-tune it afterwards anytime.

Grüße zurück aus Preußen, oder wie heißt die Gegend hier um die Hauptstadt noch gleich bei Euch? 😉
Hehe.
Ich bastle das mal rein und melde mich!
Grüße!

**Comment by DerThomasLange** [comment]
Hi, Servus Dominik,

great news, thanks for your fast reply.

I see... you're very deep in the matter!
Well, I'm just a user who want's his very basic features. But seems to be a bit tricky because of the exponential increase of the audio level, if I understood it correctly. :-D

*Juhuu* I'm looking forward for the new Feature! 
Don't hesitate to contact me if you need anyone for testings, I'm happy to help, just contact me. :-)

Vielen Dank und herzliche Grüße in die Hauptstadt,

Thomas

**Comment by shells-dw** [comment]
Moin Thomas,

see if [v3.3.0](https://github.com/shells-dw/streamdeck-totalmix/releases/tag/v3.3.0) works for you.

Grüße in den Süden

**Comment by DerThomasLange** [comment]
Dear Dominik,

hope your doing fine. :-)
Thank you very much for the insanely fast implementation of our idea.

Just so you can reconstruct my proceed: I've selected - as in your short instruction mention - "Output Channel 1" which was already a mirrored stereo channel for my speakers.

Your function "Incrementally Raise Volume" already works fine. When I press the button, the volume fader goes up by my pre-defined value.

If I try the same with "Incrementally Lower Volume", the button just do nothing at the moment. I tried it with several different values (2, 5, -2, -5, 0, 0.5, -0.5) but the result was always the same. 

See Screenshot attached.
Best regards and thank you very much!

Liebe Grüße nach Berlin und schönen Abend,

Thomas

<img width="1250" alt="Screenshot Lower Volume Streamdeck" src="https://user-images.githubusercontent.com/122398256/211832863-f00fc094-9b5f-4670-b5b6-1af275f70721.png">

**Comment by shells-dw** [comment]
Guten Abend Thomas,
it basically works for me, however I noticed that for some reason (I don't have time to figure that out right now) it seems that the selected channel reverts back to Input Channel 1 (sadly without reflecting that in the UI...) when selecting "Incrementally Lower Volume" _after_ selecting the channel. There's probably a wrong index somewhere, I'll look into it when I have time.

For now, try to select any other channel (doesn't matter which), then select Output Channel 1 again and try again.
If that doesn't do it, try deleting the button again, and when you pull it back on the deck, select "Incrementally Lower Volume" first, and select the "Output Channel 1" afterwards.
That works for me anyway.

Grüße

**Comment by shells-dw** [comment]
Moin,

probier es mit [v3.3.1](https://github.com/shells-dw/streamdeck-totalmix/releases/tag/v3.3.1), vermute das lag an dem Bug, dass der Channel auf 1 zurückgesprungen ist, der ist gefixt.

Grüße in den Süden

**Comment by DerThomasLange** [comment]
Guten Morgen Dominik,

with your new release it just works fine.
Thanks for the fast fix!
P.S. Your mentioned workaround also fixed my problem. :-)

You're creating really cool tools, keep up the great work!
If I have any further ideas in the future, I'll let you know.

One Program/Function I've always wished, that a guy like you would come up with, is a implementation for Spotify inside Recordbox, Serato, or any other DJ Software. So you could directly mix your favorite tracks on your Pioneer CDJs while streaming these songs online. If someone like you could invent this, I and many other DJs on this planet would pay hundreds of Euros for that. :-D

I'll send you a small donation, so you can finally buy yourself a respectable beer, also in Berlin.
Try Riegele or Augustiner for example. :-D

Herzliche Grüße und vielen Dank für die schnelle Umsetzung,

Thomas

**Comment by shells-dw** [comment]
Hi Thomas,

first off - thanks so much for the donation and your kind words, of course, very much appreciated ❤️ 

Well, the TOS of Spotify (and all other streaming services I'm aware of) very clearly prohibit this kind of action
<details>
  <summary>Legal-speak... excerpt of the Spotify User Guidelines:</summary>

> copying, redistributing, reproducing, "ripping," recording, transferring, performing or displaying to the public, broadcasting, or making available to the public any part of the Spotify Service or the Content, or otherwise making any use of the Spotify Service or the Content which is not expressly permitted under the Agreements or applicable law or which otherwise infringes the intellectual property rights (such as copyright) in the Spotify Service or the Content or any part of it;
>
  
</details>
Which is most certainly why such a tool isn't made yet - and even if, it would probably not be very much of a great idea to be using it to rebroadcast content from Spotify...

While I like earning money as the next person, I wouldn't want to make a business out of enabling copyright infringements - and open myself to all sorts of legal issues in the process, especially here in Germany, where the legal content... policing is such a huge business for some lawyers.

Anyway, that's not for me - but keep the ideas coming 😃 

Na, die lokalen Groß-Biere sind hier nicht so der Brüller, Riegele hab ich hier noch nie irgendwo gesehen, aber ich hab tatsächlich zuweilen ein Bayreuther. Na, ich werd die Spende jedenfalls (ordentlich versteuern 🙄 ) und vom Rest schauen, was der lokale Getränkehändler so hergibt. Nochmal vielen Dank!
Grüße!
