### ISSUE TITLE
No connection 

### ISSUE THREAD

**Issue by Tobe2d** [shells-dw/streamdeck-totalmix#25]
I have updated to v3.3.1 and still showing no connection and I cant select channel too, as you see in the screenshot below.

![image](https://user-images.githubusercontent.com/4099839/212286224-12046974-4fff-45b2-8678-f3aea6cb0519.png)

**Comment by shells-dw** [comment]
Did you enable the [second OSC listener as per the readme?](https://github.com/shells-dw/streamdeck-totalmix#setup-for-osc)?

**Comment by Tobe2d** [comment]
Thanks for the reply @shells-dw 

I am not using it with totalmix, I am using it with unreal engine and it was working perfectly until the last 2 updates I started 
 facing this issue.

I have followed this video and got it up and running since around two and half months ago and it was as easy as shown in the video: 
https://www.youtube.com/watch?v=bz7T_Tq2v-8

Now it show no connection and the Display channel is not clickable ;-(

**Comment by shells-dw** [comment]
Well, the plugin is not intended to be used with anything other than TotalMix and I'm not gonna support that for it.

However, that being said I have two other options for you:
- You can use my [Streamdeck-OSC plugin](https://github.com/shells-dw/StreamDeck-OSC) which is made to do exactly that: send OSC commands to whatever listens for them (Download is hidden in the "[Releases](https://github.com/shells-dw/StreamDeck-OSC/tree/master/Release)" subfolder
- you can revert back to the [v2 Classic version](https://github.com/shells-dw/streamdeck-totalmix-classic) of the TotalMix plugin if you insist of using it for your use case

**Comment by Tobe2d** [comment]
Thanks a lot for this help. I revertback to the v2 Classic version and it is working again ;-)
Much appreciated!
