### ISSUE TITLE
Configuration in Streamdeck not working correctly

### ISSUE THREAD

**Issue by JdotTdot098** [shells-dw/streamdeck-totalmix#27]
Hi, I'm setting this up with UE5.1 and I'm having any issue getting anything other than the first int value in UE to trigger. Even with a second button configured completely different it still just triggers switch on Int 0. 

![BP_New](https://user-images.githubusercontent.com/122623523/214110422-2f0cdf2a-c4be-4929-bb01-37f0541d8681.JPG)
![box](https://user-images.githubusercontent.com/122623523/214110658-acee7508-5ac7-4f1d-8c8b-eab7ace1f59d.JPG)
![sphere](https://user-images.githubusercontent.com/122623523/214110675-aaa19cce-8e7c-4a44-bd18-16495eb150d8.JPG)

**Comment by shells-dw** [comment]
Hi,
this is the wrong repository you've opened this issue in.

I don't know any UE, can't help you with that - and won't here, this is for the totalmix plugin, not the OSC plugin.
