### ISSUE TITLE
Using multiple RME Devices.

### ISSUE THREAD

**Issue by NOMNOMNOM117** [shells-dw/streamdeck-totalmix#28]
Could you return the option to change the port numbers. I understand the newest update defaults all the ports to 7001, 9001, 7002 and 9002. This makes it easy to use for most people, however I previously was able to use this plugin with multiple RME devices by selecting different port numbers.

**Comment by shells-dw** [comment]
Hi,
I put the "old" version on its own repository, you can use that instead https://github.com/shells-dw/streamdeck-totalmix-classic
I made it, so the classic version will install alongside the current release and not be overwritten by any future updates.
