### ISSUE TITLE
Please add Mac OS support

### ISSUE THREAD

**Issue by dcocharro** [shells-dw/streamdeck-totalmix#33]
Please, please add Mac OS support :')

**Comment by shells-dw** [comment]
Won't be happening mate. I'd need to rewrite the whole thing in something that runs on MacOS, which is nothing I'll do.

My [Loupedeck ](https://github.com/shells-dw/loupedeck-totalmix) version of the plugin supports MacOS through, so if you're willing to spend the money on the Loupedeck hardware, that should work then.

Cheers
