### ISSUE TITLE
Unable to select an entry in the "Select Function" dropdown for OSC: Control Channel and OSC: Toggle Channel Function

### ISSUE THREAD

**Issue by fgaleko** [shells-dw/streamdeck-totalmix#34]
Title. Doesn't take keyboard entry, doesn't respond to left or right click, doesn't respond to Tab on keyboard. 

StreamDeck software version 6.2.0.18816.

**Comment by innatum** [comment]
Same happened to me. I had to update the Streamdeck software and plugin, then it worked.

**Comment by shells-dw** [comment]
Sorry for responding so late, I was kind of preoccupied with work and my Fireface PSU died, took me a while to get a replacement so without the interface I couldn't really look into the issue.
However I'm back on track now and as innatum stated, with the latest Stream Deck it's working for me.

I assume it does for you too - if it doesn't, feel free to comment back on here and I'll look into it.
