### ISSUE TITLE
talkback hold feature

### ISSUE THREAD

**Issue by mauronedj** [shells-dw/streamdeck-totalmix#6]
Hi, would be really cool to have a feature that let's you hold the button to hold the talkback function (or any other feature).
Thanks,
Mauro.

**Comment by shells-dw** [comment]
Hi Mauro,

apologies for the late response, my current job comes with being away from home for extended periods of time.

I've published a new version just now - have a look in the Releases folder of this repo and check it out.
The "OSC Triger Global Function" module has a "Hold Mode" now that should be able to do exactly that (once you enabled it) for all global features.

I don't really work with Firefaces anymore, I switched to UA interfaces quite a while ago. I still have a Fireface UC laying around and used that to make the updates and verify the changes on the newest RME driver on Win 10 - however I didn't really thoroughly test those, so ... in case something doesn't work as expected, let me know.

Cheers
